import {useFieldArray, useFormContext} from "react-hook-form";
import {useEffect} from "react";
import {Button} from "reactstrap";
import {Repeat} from "react-feather";
import {useLocaleContext} from "@src/providers/LocaleProvider";
import SingleOptionField from "@src/views/pages/products/pages/view/tabs-content/attributes/form/SingleOptionField";
import {
    createOptionEntity,
    createOptionEntityWithDefaultValue
} from "@src/views/pages/products/pages/view/tabs-content/attributes/data";
import CustomCan from "@components/Authorize/CustomCan";

export default function AttributeOptionsFormDisplayer({attributeItem, permissionObject}) {
    const {translate} = useLocaleContext();

    const {
        control,
        register,
        trigger,
        formState: {errors},
        setValue,
    } = useFormContext();

    const {fields, append, replace, remove} = useFieldArray({
        control,
        name: `${attributeItem.attribute}.options`,
        keyName: 'autoGeneratedId',
        rules: {
            minLength: 1,
        }
    });

    useEffect(() => {
        const arrToReplace = attributeItem.options.map(({
                                                            id,
                                                            optionId,
                                                            optionName,
                                                            price,
                                                            priceType,
                                                            publish,
                                                            defaultOption
                                                        }) => {
            return {
                id,
                price,
                publish,
                defaultOption,
                priceType: {
                    label: priceType === 'FIXED' ? 'Number' : priceType,
                    value: priceType
                },
                option: {
                    label: optionName,
                    value: optionId,
                },
            };
        });
        replace(arrToReplace);

    }, [attributeItem]);



    const handleAddOptionsClick = async () => {
        const result = await trigger(`${attributeItem.attribute}.options`);
        if (!result) {
            return;
        }
        append(createOptionEntityWithDefaultValue());
    }

    const generateName = (fieldName, index) => {
        return `${attributeItem.attribute}.options.${index}.${fieldName}`
    }

    function handleDefaultClick(clickedIdx) {
        // set all vals to false
        fields.map((_, index)=>{
            setValue(generateName('defaultOption', index), false)
        })
        //set clicked one to true
        setValue(generateName('defaultOption', clickedIdx), true)
    }




    return (
        <>
            <input hidden {...register(`${attributeItem.attribute}.id`)} value={attributeItem.id}/>
            {fields.map((field, index) => {
                return (
                    <SingleOptionField
                        attributeItem={attributeItem}
                        field={field}
                        index={index}
                        handleDefaultClick={handleDefaultClick}
                        remove={remove}/>
                )


            })}
            <div className={"d-flex justify-content-center justify-content-sm-start"}>
                <CustomCan permissionName={permissionObject?.add}>
                    <Button type='button' className='btn-icon mt-1 d-flex gap-1' color='primary' onClick={() => handleAddOptionsClick()}>
                        <span className=' ms-25'>
                            {translate('product.common.add-option')}
                        </span>
                        <Repeat size={14}/>
                    </Button>
                </CustomCan>
            </div>
        </>
    )
}




