import {Button, Col, Row} from "reactstrap";
import CustomControlledAsyncSelectPaginate
    from "@components/controlled-inputs/CustomControlledAsyncSelectPaginateField";
import CustomControlledDropdownField from "@components/controlled-inputs/CustomControlledDropdownField";
import CustomControlledInputField from "@components/controlled-inputs/CustomControlledInputField";
import CustomControlledCheckboxInput from "@components/controlled-inputs/CustomControlledCheckboxInput";
import {CheckSquare, Square, Trash} from "react-feather";
import {useFormContext} from "react-hook-form";
import ProductOptionService from "@src/common/services/ProductOptionService";
import {useLocaleContext} from "@src/providers/LocaleProvider";
import React from "react";

function SingleOptionField({attributeItem, field, index, handleDefaultClick, remove}) {
    const {translate} = useLocaleContext();
    const {
        control,
        formState: {errors},
        watch,
    } = useFormContext();

    const generateName = (fieldName, index) => {
        return `${attributeItem.attribute}.options.${index}.${fieldName}`
    }

    const optionsErrors = errors[attributeItem.attribute]?.options[index]?.option?.value;
    const priceTypeErrors = errors[attributeItem.attribute]?.options[index]?.priceType?.value;

    const promiseOptionsCreator = (id) => {
        return (
            searchValue,
            prevOptions,
            additional,
        ) => new Promise((resolve) => {
            const prevPage = additional?.prevPage ?? 0;
            const params = {
                search: searchValue,
                page: prevPage + 1,
            };
            const page = params.page;
            const perPage = 10;
            const search = params.search;
            ProductOptionService.getPagination({
                page: page,
                search: search,
                limit: perPage,
                attribute: id
            }).then((res) => {
                const {pages, page: currentPage, items} = res.pagination;
                resolve({
                    options: items.map((item) => ({
                        label: item.value,
                        value: item.id,
                    })),
                    hasMore: currentPage < pages,
                    additional: {
                        prevPage: currentPage,
                        prevSearchValue: searchValue,
                    },
                });
            });
        })
    }

    const typeOfPriceOptions = [
        {label: 'Percentage', value: "PERCENTAGE"},
        {label: 'Number', value: "FIXED"},
    ];

    return (
        <Row key={field.autoGeneratedId}>
            <Col xs={12} md={6} lg={4} className="mb-2">
                <CustomControlledAsyncSelectPaginate
                    placeholder={translate('product-attribute.forms.option')}
                    name={generateName('option', index)}
                    label={translate('product-attribute.forms.option')}
                    control={control}
                    getOptionsPromise={promiseOptionsCreator(attributeItem.attribute)}
                    defaultOptions={[]}
                    errors={optionsErrors}
                />
            </Col>
            <Col xs={12} md={6} lg={2} className="mb-2">
                <CustomControlledDropdownField
                    name={generateName('priceType', index)}
                    label={translate('product-attribute.forms.price-type')}
                    placeholder={""}
                    control={control}
                    errors={priceTypeErrors}
                    options={typeOfPriceOptions}
                />
            </Col>
            <Col xs={12} md={6} lg={2} className="mb-2">
                <PriceFieldWithPercentageValidationLogic
                    priceFieldName={generateName('price', index)}
                    priceTypeFieldName={generateName('priceType', index)}
                />
            </Col>

            <Col xs={4} md={2} lg={1} className='d-flex justify-content-center align-items-start mt-50'>
                <CustomControlledCheckboxInput
                    control={control}
                    label={translate('forms.publish')}
                    name={generateName('publish', index)}
                />
            </Col>

            <Col xs={4} md={2} lg={1} className='d-flex justify-content-center  align-items-start mt-50'>
                <div>
                    <CustomControlledCheckboxInput
                        control={control}
                        label={translate('product-attribute.forms.default')}
                        name={generateName('defaultOption', index)}
                        onClick={() => handleDefaultClick(index)}
                        checkIcon={<CheckSquare color={'#00b602'} className='text-primary' size={30}/>}
                        unCheckIcon={<Square size={30} strokeWidth={0.5}
                        />
                        }
                    />
                </div>
            </Col>

            <ConditionalDeleteButtonForOption index={index} remove={remove} attributeItem={attributeItem}/>

            <hr className="inline-block d-lg-none my-1"/>
        </Row>

    )
}

export default SingleOptionField


function ConditionalDeleteButtonForOption({remove, index, attributeItem}) {
    const {
        watch,
    } = useFormContext();

    const attributeOptions = watch(`${attributeItem.attribute}.options`)

    return (
        attributeOptions && attributeOptions.length > 1 &&
        <Col xs={4} md={2} lg={1} className='d-flex align-items-center gap-1 justify-content-center mt-50 mt-md-0'>
            <Button color='danger' className='text-nowrap px-1 mt-75 mt-md-0' type='button' onClick={() => {
                remove(index)
            }}
                    outline>
                <Trash size={14}/>
            </Button>
        </Col>
    )
}

function PriceFieldWithPercentageValidationLogic({priceFieldName, priceTypeFieldName}){
    const {translate} = useLocaleContext();

    const {
        control,
        formState: {errors},
        watch,
    } = useFormContext();

    const priceTypeFieldValue = watch(priceTypeFieldName)?.value
    const priceTypeIsPercentage = priceTypeFieldValue === 'PERCENTAGE' ?? false;

    return(
        <CustomControlledInputField
            name={priceFieldName}
            label={translate('product-attribute.forms.price')}
            control={control}
            errors={errors}
            type="number"
            percentageValidation={priceTypeIsPercentage}
            acceptsDecimals={true}
        />
    )
}