import {Button, Card, CardBody, CardHeader, CardText, Label, TabPane} from "reactstrap";
import {Repeat} from "react-feather";
import {FormProvider} from "react-hook-form";
import ErrorAlert from "@components/ErrorAlert/ErrorAlert";
import {useLocaleContext} from "@src/providers/LocaleProvider";
import useViewAndEditDataManager from "@src/views/pages/products-attributes/edit-and-view/useViewAndEditDataManager";
import FormHeader from "@src/views/pages/products-attributes/edit-and-view/partials/form/FormHeader";
import AttributeFieldsGroup
    from "@src/views/pages/products-attributes/edit-and-view/partials/form/AttributeFieldsGroup";
import OptionFieldsGroup from "@src/views/pages/products-attributes/edit-and-view/partials/form/OptionFieldsGroup";
import Avatar from "@mui/material/Avatar";
import ParseImageUrl from "@src/common/helpers/ParseImageUrl";
import React from "react";

function ViewAndEditForm({attributeItem, refetchingAllAttributes, permissionObject}) {

    const {translate} = useLocaleContext();

    const {
        // form
        backendErrors,
        isErrorWithUpdateMutation,
        FormMethods,
        fields,
        prepareDataAndSubmit,
        handleAddOptionFormItem,
        removeOptionFormItem,
        handleDeleteAttributeItem,
    } = useViewAndEditDataManager({attributeItem, refetchingAllAttributes});


    return (
        <FormProvider {...FormMethods} >
            <form
                id={"view-and-edit-form"}
                onSubmit={FormMethods.handleSubmit(prepareDataAndSubmit)}>
                <Card className='bg-white mb-0 border-3 border-light'>

                    <FormHeader
                        iconFileUrl={attributeItem.iconFileUrl}
                        onDelete={() => {
                        handleDeleteAttributeItem(attributeItem)
                        }}
                                editPermissionName={permissionObject?.edit}
                                deletePermissionName={permissionObject?.delete}
                    />

                    <ErrorAlert isError={isErrorWithUpdateMutation} errors={backendErrors}/>

                    <CardBody className={'px-1 px-md-2'}>
                        <AttributeFieldsGroup attributeItem={attributeItem}/>

                        <h3 className='card-title text-primary font-large-1 mt-lg-1'>
                            {translate('product-attribute.forms.option-details')}
                        </h3>

                        <div className={"p-1 p-lg-3 py-2 bg-light rounded-4"}>

                            {fields.map((field, index) => {
                                    return (
                                        <OptionFieldsGroup
                                            key={field.id}
                                            field={field}
                                            index={index}
                                            handleDeleteOption={() => removeOptionFormItem(field.autoGeneratedId)}

                                        />
                                    )
                                }
                            )}


                            <div className={"d-flex justify-content-center"}>
                                <Button className='btn-icon mt-0 mt-lg-1 d-flex gap-1' color='primary'
                                        onClick={() => handleAddOptionFormItem({})}>
                                        <span className=' ms-25'>
                                            {translate('product-attribute.common.add-option')}
                                        </span>
                                    <Repeat size={14}/>
                                </Button>
                            </div>
                        </div>
                    </CardBody>
                </Card>

            </form>
        </FormProvider>
    )
}

export default ViewAndEditForm
