export const includedSettingsKeys = [
    'ENABLE_FOOTER_FLAG',
    'GUEST_CHECKOUT_REQUIRED_FIELDS',
    'ENABLE_USER_MULTI_ADDRESS',
    'ACTIVE_WISH_LIST',
    'ACTIVE_PRODUCT_REVIEW',
    'ACTIVE_ADD_TO_CART',
    'ACTIVE_REGISTER_LOGIN',
    'ACTIVE_COMING_SOON_MODE',
    'ACTIVE_MAINTENANCE_MODE',

    'ACTIVE_LEGAL_INFORMATION',
    'ACTIVE_PURCHASE_PROCESS',
    'ACTIVE_SHIPMENT_INFORMATION',
    'AUTO_CALCULATE_TAX_VALUE'
];
