

export const VENDOR_STATUS_VALUES = {
    ACCOUNT_AWAITING_APPROVAL: 'ACCOUNT_AWAITING_APPROVAL',
    ACTIVE: 'ACTIVE',
    REJECTED: 'REJECTED'
}

export const VENDOR_STATUS_OPTIONS = [
    { labelKey: 'ACCOUNT_AWAITING_APPROVAL', value: VENDOR_STATUS_VALUES.ACCOUNT_AWAITING_APPROVAL },
    { labelKey: 'ACTIVE', value: VENDOR_STATUS_VALUES.ACTIVE },
    { labelKey: 'REJECTED', value: VENDOR_STATUS_VALUES.REJECTED }
];